### ISSUE TITLE
Class vs id

### ISSUE THREAD

**Issue by Tereseus** [iLikeHotdogs/prj-rev-bwfs-dasmoto#1]
I see that you used classes instead of id's for the three sections. You did this section correctly, the vast majority of people do not do this right. The only thing I could add is that you put some section notes in your html so that it is easier to find and navigate through the element browser of the chrome console. Good job.

**Comment by iLikeHotdogs** [comment]
Hello Ted,

Thank you for the information and the suggestions on using notes...I will do that going forward.
